# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

before_install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --quiet --name TESTENV python=$TRAVIS_PYTHON_VERSION
  - source activate TESTENV
  - conda install -c conda-forge geopandas
  - conda info --all
  - conda list

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip show detectree

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source detectree -m py.test
  - flake8

after_success:
  - coverage report -m
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  user: martibosch
  password:
    secure: uTzZL1oAqrFEI45VrMXi74dtJxDVOyZsnqnxnaE8wpQwGSnL8ssuAXTJaGnzy2sGw7TYmkx4JIAI6nNG+Ewi9YDrX/uUXXdtMexts7t7/hbZDhxKH8qYGzWYyhggJwMA50Uw0uv1FVKpTJTICzfKEQzEh1uCvkwrebLV8M7XiNAJHi7OENgCY8z8H0xP2ZO4XNGK94GmOsJZBtk/l/hYMemcds98F4m2TrOWXZ0OdJUfBV1pouh2n7hXxMqT7B006RHVxXQlfA7RYneXuRNHFu7xwgIfkkmP4ixe+/fhbxYaA5pMDylsukAqU6fcrLWLFGW/cfH73h8JZm69C3OnLDDHvN9KJaf2SoHS7Zqy/e5AuJ5d7oLFQSPAGurGMAyG+UsmXWqkTbXr97eTdoO6kY21vKlhW3o2rEsAsXfUny7kepvWHUl2c9O9zR76ClIWBIVFiQ/F2sLrgNIIZ2iR3gG3jXINVJOtp3dseyKMbMebqaz7zx/dv7QSzuzWGlYrSaUKlifDfdm599dYYyM3gRI8ufAgMDjVV6YfjWpZVC0GoG5z/3DioPso+PaNqwbND5w/yDKyTL15PDBdmkYy/RDaotXnFmRDGyfYb9R/83d0GVlJGefnk712+gs5yMG0BVEu3JJcLOPwqGdZkkcH2L6+76PMgO6zdT5NJeBqdDQ=
